### PR TITLE
[WIP] RAINCATCH-310 Create a nightwatch test for the creation of a new user in the portal

### PR DESCRIPTION
**Pull request by ghost**
# MOTIVATION
Authentication testing for user to
Portal App
- [ ] log in
- [ ] log out
- [ ] change password

Mobile App
- [ ] log in with new password
- [ ] log out
---
**Run the tests use:**
`grunt uart:local`

### CODE REVIEW

**Review by witmicko — APPROVED** [review]
LTGM

**Comment by secondsun** [comment]
The tests should probably check that the raincatcher app is running locally before they start running, otherwise everything takes forever to get results that aren't useful.

**Comment by secondsun** [comment]
When I try to run the tests, they all fail.

I do have the portal running locally.  The test suite opens the portal correctly, but then it opens an empty windows with no URL and begins to fail tests.

**Comment by secondsun** [comment]
For what it is worth, in the future you might want to decompose the PR a bit.  There are a lot of new files and it might be better to see more how you thought about things when you were putting the code together.

**Comment by ghost** [comment]
> When I try to run the tests, they all fail.
> 
> I do have the portal running locally. The test suite opens the portal correctly, but then it opens an empty windows with no URL and begins to fail tests.

Thats depends on firefox version too **51.0.1**
try `grunt uart:local --browser=chrome` to run with chrome
It should pass with chrome

---
Starting selenium server... started - PID:  51520


  Authentication
    Portal App
      ✓ Navigate to the portal's log in page
      ✓ Wait until login page loaded
      ✓ Fill in wrong user credentials
      ✓ Error message is displayed
      ✓ Login with correct credentials
      ✓ Verify scheduler page is displayed
      - Navigate to settings page
      - Change user password
      - Logout from portal
      - Login with new credentials
      - Verify scheduler page is displayed
      - Login with old credentials
      - Error message is displayed
    Mobile App
      - Open Mobile App
      - Login with old password
      - Verify login error message visible
      - Login with new password
      - Verify workorder page is displayed
      - Verify workorder page is displayed
      - Logout from portal


  6 passing (8s)
  14 pending


Done.

**Comment by ghost** [comment]
> For what it is worth, in the future you might want to decompose the PR a bit. There are a lot of new files and it might be better to see more how you thought about things when you were putting the code together.

Agree. Added to much files for 1 commit only

**Comment by secondsun** [comment]
I tried running with chrome, same result.

**Comment by secondsun** [comment]
Just checked, my firefox version is 51.0.1

**Pull request closed without merging**
